### ISSUE TITLE
Items not loading correctly!

### ISSUE THREAD

**Issue by thecaalypso** [Querrin/EndShop#9]
Hi, I've got an issue in your plugin... When I add item to the list at 1st position (so slot: 0) it's not being displayed...
Any clue how to fix this issue?
Thanks for response,
Calypso

PS: File & Screen below
[Files.zip](https://github.com/Querrin/EndShop/files/4740729/Files.zip)

**Comment by Querrin** [comment]
I don't think the screenshot matches the config file. both `cobblestone` and `stone` items are set to slot 1, so they should display in second slot.

**Comment by thecaalypso** [comment]
I've made a new shop file, so it's easy to see, but still, I've tried to set slot on items from 0 and more as well as from 1 and more... Nothingh works, shop is displaying from 2nd item in config...

PS: attached new files (Gui shows 1st item as Spruce, but is should be oak leaves)
[files.zip](https://github.com/Querrin/EndShop/files/4740785/files.zip)

**Comment by Querrin** [comment]
I misunderstood your question, it is indeed a bug. I will fix it in 1.4.3

You can join the Discord server to know instantly when I will release the new version.

**Comment by Querrin** [comment]
Fixed in v1.4.3

**Comment by thecaalypso** [comment]
Ok ok, thanks <3
